eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcv123bnm
    url: jdbc:mysql://192.168.31.90/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 192.168.31.90
    port: 5672
    username: admin
    password: admin
server:
  port: 8088
env: dev
